language:  python

python:
  - "2.7"

script: "bash build_test.sh plone-4.3"

notifications:
  irc:
    channels:
      - "irc.freenode.org#sprint"
    template:
      - "%{repository}/#%{build_number}/%{branch} (%{author}): %{message} %{build_url}"
